name: Update secondary

on:
  push:
    branches:
      - main

jobs:
  update-cms-master:
    name: Merge main into secondary after anything is pushed
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'secondary'
