# GitHub action to sync branches secondary on pushes to main
name: Merge main back to secondary
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.JENKINS_APP_ID }}
          private_key: ${{ secrets.JENKINS_APP_KEY }}

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Merge main -> secondary
        if: github.ref == 'refs/heads/main'
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: secondary
          message: Merge main into secondary
          github_token: ${{ steps.generate_token.outputs.token }}
